#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Sep 01, 2022 01:24:15 AM -03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+660+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr50 \
        -borderwidth 2 -relief groove -width 575 -height 385 
    vTcl:DefineAlias "$top.tFr50" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr50
    ttk::label $site_3_0.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI Symbol} -size 17} -relief flat -anchor w \
        -justify left -text Nombre -compound left 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI Symbol} -size 17} -relief flat -anchor w \
        -justify left -text Apellido -compound left 
    vTcl:DefineAlias "$site_3_0.tLa53" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI Symbol} -size 17} -relief flat -anchor w \
        -justify left -text Código -compound left 
    vTcl:DefineAlias "$site_3_0.tLa54" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn55 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn55" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn56 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn56" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn57 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn57" "TEntry3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu58 \
        -takefocus {} -text Agregar -compound left 
    vTcl:DefineAlias "$site_3_0.tBu58" "btnAgregar" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu59 \
        -takefocus {} -text Salir -compound left 
    vTcl:DefineAlias "$site_3_0.tBu59" "btnSalir" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 0 -relx 0.261 -y 0 -rely 0.13 -width 0 \
        -relwidth 0.162 -height 0 -relheight 0.101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 0 -relx 0.261 -y 0 -rely 0.286 -width 0 \
        -relwidth 0.165 -height 0 -relheight 0.101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 0 -relx 0.261 -y 0 -rely 0.442 -width 0 \
        -relwidth 0.148 -height 0 -relheight 0.101 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn55 \
        -in $site_3_0 -x 0 -relx 0.504 -y 0 -rely 0.156 -width 0 \
        -relwidth 0.219 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn56 \
        -in $site_3_0 -x 0 -relx 0.504 -y 0 -rely 0.312 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn57 \
        -in $site_3_0 -x 0 -relx 0.504 -y 0 -rely 0.468 -width 0 \
        -relwidth 0.219 -height 0 -relheight 0.055 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu58 \
        -in $site_3_0 -x 0 -relx 0.261 -y 0 -rely 0.727 -width 106 \
        -relwidth 0 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 0 -relx 0.557 -y 0 -rely 0.727 -width 106 \
        -relwidth 0 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    ttk::label $top.tLa51 \
        -background #8ce7f0 -foreground $vTcl(actual_gui_fg) \
        -font {-family {Segoe UI Black} -size 21 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor center -justify left -text {Agregar Figurita} \
        -compound left 
    vTcl:DefineAlias "$top.tLa51" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr50 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.133 -width 0 -relwidth 0.958 \
        -height 0 -relheight 0.856 -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.992 -height 0 \
        -relheight 0.131 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

